version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/PuerkitoBio/goquery
    versions:
    - ">= 1.5.a, < 1.6"
  - dependency-name: github.com/rs/zerolog
    versions:
    - 1.20.0
